FROM jenkins/jenkins:lts

USER root

# Instalar Python e dependências
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Criar link simbólico para python apontar para python3
RUN ln -s /usr/bin/python3 /usr/bin/python

USER jenkins
