name: CI/CD Simple

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.11"

jobs:
  # Job 1: Testes Básicos
  tests:
    name: "Executar Testes"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
    
    - name: Configurar Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Instalar dependências básicas
      run: |
        python -m pip install --upgrade pip
        pip install pygame>=2.6.0
        pip install coverage pytest pytest-cov
    
    - name: Testar imports básicos
      run: |
        echo "Configurando PYTHONPATH..."
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        
        echo "Testando imports principais..."
        python -c "import war; print('war module OK')"
        python -c "from war.card import Card; print('Card OK')"
        python -c "from war.player import Player; print('Player OK')"
        python -c "from war.game import Game; print('Game OK')"
        python -c "from war.territory import Territory; print('Territory OK')"
    
    - name: Executar testes unitários
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        python -m unittest discover tests/ --verbose --start-directory=. --pattern="test*.py"